[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "clinicult"
authors = [{name = "Moshe Reubinoff", email = "reubinoff@gmail.com"}]
dynamic = ["version", "description"]
